// Generated by ci-agent — do not edit by hand, regenerate instead.
// Validate: JenkinsPipelineUnit (see docs/JENKINS_TESTING.md).

pipeline {
  agent { docker { image 'python:3.11-slim' } }
  // branches: main (configure multibranch or triggers in Jenkins)
  stages {
    stage('Lint') {
      steps {
        checkout scm
        sh 'pip install ruff==0.4.0'
        sh 'ruff check .'
        sh 'pip install flake8==7.0.0'
        sh 'flake8 .'
        sh 'echo \'actionlint validates github workflows only — skipped on jenkins\''
        sh 'pip install yamllint==1.35.0'
        sh 'yamllint .'
        sh 'sudo apt-get update && sudo apt-get install -y shellcheck'
        sh 'git ls-files \'*.sh\' | grep -q . && (git ls-files \'*.sh\' | xargs -r shellcheck) || echo \'no shell files, skipping shellcheck\''
        sh 'ls Dockerfile* >/dev/null 2>&1 && (mkdir -p $HOME/.local/bin && curl -sSfL -o /tmp/hadolint.dl https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 && (tar -xzf /tmp/hadolint.dl -C $HOME/.local/bin hadolint 2>/dev/null || cp /tmp/hadolint.dl $HOME/.local/bin/hadolint) && chmod +x $HOME/.local/bin/hadolint && export PATH=$HOME/.local/bin:$PATH && hadolint Dockerfile) || echo \'no Dockerfile, skipping hadolint\''
      }
    }
    stage('Test') {
      steps {
        sh 'pip install -r requirements.txt'
        sh 'pip install pytest==8.2.0'
        sh 'pytest -q'
      }
    }
    stage('Security') {
      steps {
        sh 'pip install -r requirements.txt'
        sh 'pip install bandit==1.7.5'
        sh 'bandit -r . -q'
        sh 'pip install pip-audit==2.7.0'
        sh 'pip-audit'
        echo 'TODO: install gitleaks on jenkins agent'
      }
    }
  }
  post {
    always {
      echo 'ci-agent evidence archived'
    }
  }
}
