"""Azure Pipelines renderer (Phase 7). Translates IR jobs to azure-pipelines.yml."""
from __future__ import annotations

import yaml

from ..common.models import PipelineIR

HEADER = """# Generated by ci-agent — do not edit by hand, regenerate instead.
"""

SETUP_TASKS: dict[str, dict[str, str]] = {
    "python": {"task": "UsePythonVersion@0", "input": "versionSpec"},
    "node": {"task": "NodeTool@0", "input": "versionSpec"},
    "go": {"task": "GoTool@0", "input": "version"},
    "java": {"task": "JavaToolInstaller@0", "input": "versionSpec"},
    "csharp": {"task": "UseDotNet@2", "input": "version"},
}

TOOL_GUARDS: dict[str, str] = {
    "shellcheck": "git ls-files '*.sh' | grep -q . && ({cmd}) || echo 'no shell files, skipping shellcheck'",
    "hadolint": "ls Dockerfile* >/dev/null 2>&1 && ({cmd}) || echo 'no Dockerfile, skipping hadolint'",
    "actionlint": "ls .github/workflows/*.y*ml >/dev/null 2>&1 && ({cmd}) || echo 'no github workflows, skipping actionlint'",
}


def filename(ir: PipelineIR) -> str:
    return "azure-pipelines.yml"


def render(ir: PipelineIR) -> tuple[str, list[str]]:
    notes: list[str] = list(ir.metadata.get("notes", []))
    push_branches = ir.triggers.get("push", {}).get("branches", ["main"])
    pr_branches = ir.triggers.get("pull_request", {}).get("branches", ["main"])

    doc: dict = {
        "trigger": {"branches": {"include": push_branches}},
        "pr": {"branches": {"include": pr_branches}},
        "pool": {"vmImage": "ubuntu-latest"},
        "jobs": [],
    }
    for job in ir.jobs:
        job_doc: dict = {"job": _job_key(job.id), "displayName": job.name}
        if job.needs:
            job_doc["dependsOn"] = [_job_key(n) for n in job.needs]
        steps: list[dict] = []
        for step in job.steps:
            steps.extend(_render_step(step, notes))
        if job.artifacts:
            steps.append({
                "task": "PublishBuildArtifacts@1",
                "displayName": "Publish evidence artifacts",
                "inputs": {"PathtoPublish": ".", "ArtifactName": "ci-evidence"},
                "condition": "always()",
            })
        job_doc["steps"] = steps
        doc["jobs"].append(job_doc)

    body = yaml.safe_dump(doc, sort_keys=False, width=1000, default_flow_style=False)
    return HEADER + body, notes


def _job_key(job_id: str) -> str:
    return "".join(c if c.isalnum() or c == "_" else "_" for c in job_id)


def _render_step(step, notes: list[str]) -> list[dict]:
    # Checkout uses-step -> native checkout.
    if step.uses.startswith("actions/checkout@"):
        fetch = step.with_args.get("fetch-depth")
        node: dict = {"checkout": "self", "displayName": step.name}
        if fetch:
            node["fetchDepth"] = fetch
        return [node]
    # Setup steps -> native tool installer tasks.
    if step.tool == "setup":
        eco = step.with_args.get("ecosystem", "")
        version = step.with_args.get("version", "")
        mapping = SETUP_TASKS.get(eco)
        if mapping:
            return [{
                "task": mapping["task"],
                "displayName": step.name,
                "inputs": {mapping["input"]: version},
            }]
        notes.append(f"azure: no native setup task for '{eco}' — version {version} assumed on agent")
        return [{"script": f"echo 'assuming {eco} {version} on agent'", "displayName": step.name}]
    # Official action-installs have no azure equivalent -> shell fallback note.
    if step.uses:
        notes.append(f"azure: action '{step.uses}' has no native task — install the tool via script instead")
        return [{
            "script": f"echo 'TODO: install {step.tool} on azure agent'",
            "displayName": step.name,
        }]
    run = step.run
    guard = TOOL_GUARDS.get(step.tool or "")
    if guard and step.condition:
        run = guard.format(cmd=run)
    node = {"script": run, "displayName": step.name}
    if step.env:
        node["env"] = dict(step.env)
    return [node]
