"""Human-readable explanations (PDF §5: "explain the result").

Every generated pipeline ships with a reviewer summary: what was built, why
each tool was chosen (with sources), what policy decided, and what happens
next. Used by the API, the UI, and PR bodies.
"""
from __future__ import annotations

from ..common.models import (
    CandidatePlan,
    PipelineIR,
    PolicyDecision,
    RepositoryContext,
    UserIntent,
    ValidationResult,
)
from ..security.redact import redact


def explain(
    intent: UserIntent,
    plan: CandidatePlan,
    policy: PolicyDecision,
    ir: PipelineIR,
    results: list[ValidationResult] | None = None,
    approval_state: str = "not-required",
) -> str:
    results = results or []
    lines = [
        f"# CI plan: {ir.name} ({ir.platform})",
        "",
        f"Requested capabilities: {', '.join(intent.capabilities) or 'none'}.",
        f"Policy decision: **{policy.decision.value}** (evaluated by {policy.evaluator}).",
        "",
        "## Jobs",
    ]
    for job in ir.jobs:
        needs = f" (needs: {', '.join(job.needs)})" if job.needs else ""
        lines.append(f"### {job.name} `{job.id}`{needs}")
        for step in job.steps:
            what = step.uses or f"`{step.run[:100]}`"
            lines.append(f"- **{step.name}** — {what}")
        lines.append("")
    lines.append("## Tool choices")
    lines.append("")
    lines.append("| tool | capability | version | why |")
    lines.append("|---|---|---|---|")
    for tool in plan.tools:
        lines.append(f"| {tool.name} | {tool.capability} | {tool.version} | {tool.reason} |")
    lines.append("")
    if plan.notes:
        lines.append("## Planner notes")
        lines.append("")
        lines += [f"- {note}" for note in plan.notes]
        lines.append("")
    if policy.deny or policy.approval_reasons:
        lines.append("## Policy findings")
        lines.append("")
        for finding in list(policy.deny) + list(policy.approval_reasons):
            lines.append(f"- `{finding.rule}` — {finding.message}")
        lines.append("")
    if results:
        lines.append("## Validation")
        lines.append("")
        for result in results:
            status = "PASS" if result.passed else "FAIL"
            lines.append(f"- {result.validator} ({result.version or 'n/a'}): **{status}**")
            for finding in result.errors[:10]:
                lines.append(f"  - error: {finding.message}")
                if finding.remediation:
                    lines.append(f"    fix: {finding.remediation}")
        lines.append("")
    lines.append("## Approval")
    lines.append("")
    lines.append(f"State: **{approval_state}**.")
    if approval_state == "awaiting-approval":
        lines.append("A reviewer must approve before anything is committed or opened as a PR.")
    lines.append("")
    lines.append(f"_Generated by ci-agent (planner: {intent.planner or 'n/a'}). "
                 "Action versions are tag-pinned; harden to SHAs before production._")
    return redact("\n".join(lines))


def short_summary(intent: UserIntent, ir: PipelineIR) -> str:
    jobs = ", ".join(job.id for job in ir.jobs)
    return redact(f"CI ({ir.platform}): {jobs} for [{', '.join(intent.capabilities)}]")


def describe_repo(ctx: RepositoryContext) -> str:
    langs = ", ".join(l.name for l in ctx.languages) or "unknown stack"
    ci = f"{len(ctx.existing_ci)} existing workflow(s)" if ctx.existing_ci else "no existing CI"
    return f"{langs}; {ctx.total_files} files; {ci}; commit {ctx.commit_sha[:12]}"
