"""GitHub Actions renderer (Phase 1 primary target)."""
from __future__ import annotations

import yaml

from ..common.models import PipelineIR

HEADER = """# Generated by ci-agent — do not edit by hand, regenerate instead.
# Action refs are tag-pinned; harden to immutable SHAs before production:
#   python backend/scripts/pin_actions.py --workflow {filename}
"""


def filename(ir: PipelineIR) -> str:
    custom = (ir.metadata.get("workflow_filename") or "").strip()
    if custom:
        return custom if custom.startswith(".github/workflows/") else f".github/workflows/{custom}"
    return ".github/workflows/ci.yml"


def render(ir: PipelineIR) -> tuple[str, list[str]]:
    notes: list[str] = list(ir.metadata.get("notes", []))
    push_branches = ir.triggers.get("push", {}).get("branches", ["main"])
    pr_branches = ir.triggers.get("pull_request", {}).get("branches", ["main"])

    doc: dict = {
        "name": ir.name,
        "on": {
            "push": {"branches": push_branches},
            "pull_request": {"branches": pr_branches},
        },
        "permissions": dict(ir.permissions),
        "jobs": {},
    }
    for job in ir.jobs:
        job_doc: dict = {"runs-on": job.runs_on}
        if job.needs:
            job_doc["needs"] = list(job.needs)
        if job.environment:
            job_doc["environment"] = job.environment
        steps: list[dict] = []
        for step in job.steps:
            step_doc: dict = {"name": step.name}
            if step.id:
                step_doc["id"] = step.id
            if step.condition:
                step_doc["if"] = step.condition
            if step.uses:
                step_doc["uses"] = step.uses
                with_args = {k: v for k, v in step.with_args.items() if k not in ("ecosystem", "version")}
                if with_args:
                    step_doc["with"] = with_args
            elif step.run:
                step_doc["run"] = step.run
            if step.env:
                step_doc["env"] = dict(step.env)
            steps.append(step_doc)
        job_doc["steps"] = steps
        doc["jobs"][job.id] = job_doc

    body = yaml.safe_dump(doc, sort_keys=False, width=1000, default_flow_style=False)
    content = HEADER.format(filename=filename(ir)) + body
    return content, notes
