"""GitLab CI renderer (Phase 7). Translates IR jobs to .gitlab-ci.yml."""
from __future__ import annotations

import re

import yaml

from ..common.models import PipelineIR

HEADER = """# Generated by ci-agent — do not edit by hand, regenerate instead.
"""

IMAGES: dict[str, str] = {
    "python": "python:{ver}-slim",
    "node": "node:{ver}-slim",
    "go": "golang:{ver}",
    "java": "eclipse-temurin:{ver}-jdk",
    "csharp": "mcr.microsoft.com/dotnet/sdk:{ver}",
    "ruby": "ruby:{ver}",
    "rust": "rust:{ver}",
    "php": "php:{ver}-cli",
}
DEFAULT_IMAGE = "alpine:3.19"

TOOL_GUARDS: dict[str, str] = {
    "shellcheck": "git ls-files '*.sh' | grep -q . && ({cmd}) || echo 'no shell files, skipping shellcheck'",
    "hadolint": "ls Dockerfile* >/dev/null 2>&1 && ({cmd}) || echo 'no Dockerfile, skipping hadolint'",
    "actionlint": "echo 'actionlint validates github workflows only — skipped on gitlab'",
}


def filename(ir: PipelineIR) -> str:
    return ".gitlab-ci.yml"


def render(ir: PipelineIR) -> tuple[str, list[str]]:
    notes: list[str] = list(ir.metadata.get("notes", []))
    branches = ir.triggers.get("push", {}).get("branches", ["main"])
    branch_re = "^(%s)$" % "|".join(re.escape(b) for b in branches)

    doc: dict = {
        "workflow": {"rules": [{"if": f"$CI_COMMIT_BRANCH =~ /{branch_re}/", "when": "always"}]},
        "stages": [job.id for job in ir.jobs],
    }
    image, image_note = _image_for(ir)
    if image_note:
        notes.append(image_note)

    for job in ir.jobs:
        job_doc: dict = {"stage": job.id, "image": image}
        if job.needs:
            job_doc["needs"] = list(job.needs)
        if job.environment:
            job_doc["environment"] = {"name": job.environment}
        scripts: list[str] = []
        for step in job.steps:
            script = _render_step(step, notes)
            if script:
                scripts.append(script)
        job_doc["script"] = scripts or ["echo 'no steps'"]
        if any(s.tool == "docker" for s in job.steps):
            job_doc["services"] = ["docker:dind"]
            notes.append(f"gitlab: job '{job.id}' uses docker:dind service")
        if job.artifacts:
            job_doc["artifacts"] = {"paths": list(job.artifacts), "when": "always"}
        doc[job.id] = job_doc

    body = yaml.safe_dump(doc, sort_keys=False, width=1000, default_flow_style=False)
    return HEADER + body, notes


def _image_for(ir: PipelineIR) -> tuple[str, str]:
    setups = [
        (s.with_args.get("ecosystem", ""), s.with_args.get("version", ""))
        for job in ir.jobs for s in job.steps if s.tool == "setup"
    ]
    if not setups:
        return DEFAULT_IMAGE, ""
    eco, ver = setups[0]
    template = IMAGES.get(eco)
    if not template:
        return DEFAULT_IMAGE, f"gitlab: no image mapping for '{eco}' — using {DEFAULT_IMAGE}"
    match = re.match(r"(\d+(?:\.\d+)?)", ver or "")
    tag = match.group(1) if match else "latest"
    image = template.format(ver=tag)
    note = ""
    if len(setups) > 1:
        note = f"gitlab: multi-ecosystem repo, shared image {image} (first ecosystem wins)"
    return image, note


def _render_step(step, notes: list[str]) -> str:
    # GitLab auto-checkouts; setup steps are covered by the job image.
    if step.uses.startswith("actions/checkout@") or step.tool == "setup":
        return ""
    if step.uses:
        notes.append(f"gitlab: action '{step.uses}' has no gitlab equivalent — install the tool via script instead")
        return f"echo 'TODO: install {step.tool} on gitlab runner'"
    run = step.run
    guard = TOOL_GUARDS.get(step.tool or "")
    if guard and step.condition:
        run = guard.format(cmd=run) if "{cmd}" in guard else guard
    if step.env:
        exports = " ".join(f"{k}={v}" for k, v in step.env.items())
        run = f"export {exports} && {run}"
    return run
