"""Jenkins declarative pipeline renderer (Phase 7).

Emits a Jenkinsfile. Tool setup on Jenkins is controller-specific, so setup
steps become version-pinned docker agents when the repo has a single known
ecosystem, else explicit notes. Validate with JenkinsPipelineUnit
(see docs/JENKINS_TESTING.md + examples/jenkins/).
"""
from __future__ import annotations

import re

from ..common.models import PipelineIR

HEADER = """// Generated by ci-agent — do not edit by hand, regenerate instead.
// Validate: JenkinsPipelineUnit (see docs/JENKINS_TESTING.md).
"""

IMAGES: dict[str, str] = {
    "python": "python:{ver}-slim",
    "node": "node:{ver}-slim",
    "go": "golang:{ver}",
    "java": "eclipse-temurin:{ver}-jdk",
    "csharp": "mcr.microsoft.com/dotnet/sdk:{ver}",
    "ruby": "ruby:{ver}",
    "rust": "rust:{ver}",
    "php": "php:{ver}-cli",
}

TOOL_GUARDS: dict[str, str] = {
    "shellcheck": "git ls-files '*.sh' | grep -q . && ({cmd}) || echo 'no shell files, skipping shellcheck'",
    "hadolint": "ls Dockerfile* >/dev/null 2>&1 && ({cmd}) || echo 'no Dockerfile, skipping hadolint'",
    "actionlint": "echo 'actionlint validates github workflows only — skipped on jenkins'",
}


def filename(ir: PipelineIR) -> str:
    return "Jenkinsfile"


def render(ir: PipelineIR) -> tuple[str, list[str]]:
    notes: list[str] = list(ir.metadata.get("notes", []))
    agent_block, agent_note = _agent_for(ir)
    if agent_note:
        notes.append(agent_note)

    chunks: list[str] = [HEADER, "pipeline {", f"  {agent_block}"]
    branches = ir.triggers.get("push", {}).get("branches", ["main"])
    chunks.append(f"  // branches: {', '.join(branches)} (configure multibranch or triggers in Jenkins)")
    chunks.append("  stages {")
    for index, job in enumerate(ir.jobs):
        chunks.append(f"    stage('{_gstr(job.name)}') {{")
        if job.environment:
            chunks.append("      // environment protection is configured on the Jenkins controller")
        chunks.append("      steps {")
        if index == 0:
            chunks.append("        checkout scm")
        for step in job.steps:
            for line in _render_step(step, notes):
                chunks.append(f"        {line}")
        chunks.append("      }")
        chunks.append("    }")
    chunks.append("  }")
    artifacts = sorted({a for job in ir.jobs for a in job.artifacts})
    chunks.append("  post {")
    chunks.append("    always {")
    if artifacts:
        patterns = ", ".join(f"'{a}'" for a in artifacts)
        chunks.append(f"      archiveArtifacts artifacts: {patterns}, allowEmptyArchive: true")
    chunks.append("      echo 'ci-agent evidence archived'")
    chunks.append("    }")
    chunks.append("  }")
    chunks.append("}")
    chunks.append("")
    return "\n".join(chunks), notes


def _agent_for(ir: PipelineIR) -> tuple[str, str]:
    setups = [
        (s.with_args.get("ecosystem", ""), s.with_args.get("version", ""))
        for job in ir.jobs for s in job.steps if s.tool == "setup"
    ]
    ecos = {eco for eco, _ in setups}
    if len(ecos) == 1:
        eco = next(iter(ecos))
        ver = next(v for e, v in setups if e == eco)
        template = IMAGES.get(eco)
        if template:
            match = re.match(r"(\d+(?:\.\d+)?)", ver or "")
            tag = match.group(1) if match else "latest"
            return f"agent {{ docker {{ image '{template.format(ver=tag)}' }} }}", ""
    if ecos:
        return "agent any", f"jenkins: multi-ecosystem ({sorted(ecos)}) — using 'agent any', ensure tools on agents"
    return "agent any", ""


def _render_step(step, notes: list[str]) -> list[str]:
    if step.uses.startswith("actions/checkout@") or step.tool == "setup":
        return []
    if step.uses:
        notes.append(f"jenkins: action '{step.uses}' has no jenkins equivalent — install the tool via shell instead")
        return [f"echo 'TODO: install {_gstr(step.tool or step.uses)} on jenkins agent'"]
    run = step.run
    guard = TOOL_GUARDS.get(step.tool or "")
    if guard and step.condition:
        run = guard.format(cmd=run) if "{cmd}" in guard else guard
    if step.env:
        exports = " ".join(f"{k}={v}" for k, v in step.env.items())
        run = f"export {exports} && {run}"
    if "\n" in run:
        return ["sh '''", *[f"      {line}" for line in run.splitlines()], "    '''"]
    return [f"sh '{_gstr(run)}'"]


def _gstr(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "\\'")
